### PR TITLE
Add header in /v2/subscriptions POST response

### PR DESCRIPTION
**Pull request by taliaga**

### CODE REVIEW

**Comment by jmcanterafonseca** [comment]
@taliaga  as this file is automatically generated this contribution should be provided in the original Apiary file that is still in fiware-orion repo, I believe we should move that NGSIv2 spec to this repo ... but I would like to know @fgalan opinion

**Comment by fgalan** [comment]
As far as I understand this is already included in the original Apiary file, in particular [here](https://github.com/telefonicaid/fiware-orion/blob/master/doc/apiary/v2/fiware-ngsiv2-2.0-2018_09_15.apib#L1898):

```
+ Response 201

    + Headers

            Location: /v2/subscriptions/abcde98765
```

Please @taliaga have a look in order to see if it's ok there. In positive case, maybe somethign is failing in the automatic generation of OpenAPI/ngsiv2/ngsiv2-openapi.json.

**Comment by taliaga** [comment]
I don't know how you guys orchestrate the creation files until the final output of the specification. In fact I didn't know this file was also autogenerated :) (so feel free to close this PR!)

Sounds reasonable to me, something may be wrong in the generation process. Which tools are you using to convert formats?

**Comment by jmcanterafonseca** [comment]
@caa06d9c can this PR be closed?

/cc @jason-fox

**Pull request closed without merging**
